mysql4confluence:
  build: mysql/
  environment:
    - DB_USER=confluence_user
    - DB_PASS=password
    - DB_NAME=confluence
  volumes:
    - /data/docker/confluence/mysql:/var/lib/mysql
confluence:
  build: confluence/
  links:
    - mysql4confluence:mysql
  environment:
    - DB_TYPE=mysql
  ports:
    - "8090:8090"
  volumes:
    - /data/docker/confluence/confluence:/var/atlassian/application-data/confluence
    - /data/docker/confluence/backup:/var/atlassian/application-data/confluence/backups

