mysql4confluence:
  build: mysql/
  environment:
    - DB_USER=confluence_user
    - DB_PASS=password
    - DB_NAME=confluence
  volumes:
    - /data/confluence/mysql:/var/lib/mysql
confluence:
  build: confluence/
  links:
    - mysql4confluence:mysql
  environment:
    - DB_TYPE=mysql
    - JAVA_MEMORY_OPTS=-Xms1536m -Xmx1536m -XX:+UseG1GC
  ports:
    - "80:8090"
  volumes:
    - /data/confluence/confluence:/var/atlassian/application-data/confluence
    - /backup/confluence/backup:/var/atlassian/application-data/confluence/backups

