#!/bin/bash -e

CONF_CONFIG_FILE="${CONF_HOME_DIR}/confluence.cfg.xml"

# Database variables
DB_TYPE=${DB_TYPE:-}
DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-}
DB_NAME=${DB_NAME:-}
DB_USER=${DB_USER:-}
DB_PASS=${DB_PASS:-}
#DB_POOL=${DB_POOL:-20}

# Check if a mysql container has been linked
if [ -n "${MYSQL_PORT_3306_TCP_ADDR}" ]; then
    DB_TYPE=${DB_TYPE:-mysql}
    DB_HOST=${DB_HOST:-${MYSQL_PORT_3306_TCP_ADDR}}
    DB_PORT=${DB_PORT:-${MYSQL_PORT_3306_TCP_PORT}}
    DB_USER=${DB_USER:-${MYSQL_ENV_DB_USER}}
    DB_PASS=${DB_PASS:-${MYSQL_ENV_DB_PASS}}
    DB_NAME=${DB_NAME:-${MYSQL_ENV_DB_NAME}}
fi

# Check DB_TYPE
case "${DB_TYPE}" in 
    mysql)
        DB_PORT=${DB_PORT:-3306}
        echo "DB_TYPE=${DB_TYPE}"
        echo "DB_HOST=${DB_HOST}"
        echo "DB_PORT=${DB_PORT}"
        echo "DB_NAME=${DB_NAME}"
        echo "DB_USER=${DB_USER}"
        echo "DB_PASS=${DB_PASS}"
        ;;
    *)
        echo "Currently only MySQL is supported as database type."
        exit 1
        ;;
esac

#
if [ ! -f $CONF_CONFIG_FILE ]; then
    # Initial Setup Confluence
    chown -R 1000:1000 ${CONF_HOME_DIR} 
    ${CONF_INSTALL_DIR}/bin/start-confluence.sh -fg
    exit 0
fi

# Configuring a MySQL Datasource in Apache Tomcat
XML_PATH="confluence-configuration/properties"

# Update Config file
# backup
cp ${CONF_CONFIG_FILE} ${CONF_CONFIG_FILE}.bak

# update configfile
xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.connection.driver_class']" \
  --subnode "${XML_PATH}"  --type elem -n property -v "com.mysql.jdbc.Driver" \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.connection.driver_class ${CONF_CONFIG_FILE}

xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.connection.url']" \
  --subnode "${XML_PATH}"  --type elem -n property -v "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sessionVariables=storage_engine%3DInnoDB&amp;useUnicode=true&amp;characterEncoding=utf8" \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.connection.url ${CONF_CONFIG_FILE}

xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.connection.username']" \
  --subnode "${XML_PATH}"  --type elem -n property -v ${DB_USER} \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.connection.username ${CONF_CONFIG_FILE}

xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.connection.password']" \
  --subnode "${XML_PATH}"  --type elem -n property -v ${DB_PASS} \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.connection.password ${CONF_CONFIG_FILE}

xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.setup']" \
  --subnode "${XML_PATH}"  --type elem -n property -v true \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.setup ${CONF_CONFIG_FILE}

xmlstarlet ed --inplace \
  --delete "${XML_PATH}/property[@name='hibernate.dialect']" \
  --subnode "${XML_PATH}"  --type elem -n property -v "com.atlassian.hibernate.dialect.MySQLDialect" \
  --insert  "${XML_PATH}/property[last()]" --type attr -n name -v hibernate.dialect ${CONF_CONFIG_FILE}



# SET JAVA OPTION
JAVA_MEMORY_OPTS=${JAVA_MEMORY_OPTS:-"-Xms1024m -Xmx1024m -XX:+UseG1GC"}
#sed -i.bak -e "s/^export CATALINA_OPTS/CATALINA_OPTS='\${CATALINA_OPTS} \${DOCKER_JAVA_OPTS}'; echo \$CATALINA_OPTS ; export CATALINA_OPTS/" ${CONF_INSTALL_DIR}/bin/setenv.sh
sed -i.bak -e "s/-Xms1024m -Xmx1024m -XX:+UseG1GC/${JAVA_MEMORY_OPTS}/" ${CONF_INSTALL_DIR}/bin/setenv.sh

# start server
${CONF_INSTALL_DIR}/bin/start-confluence.sh -fg

